# Default values for overops-collector.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
 # Used only when deploying with the overops/overops chart.
 enableStorageServer: false
 enableStorageServerS3: false

# Overops Config settings
overops:
  backendURL: 
  storageTestURL:
  serverName:
  jvmHeapSize: "1G" # Overops collector requires 4G heap size .
  serviceKey:
  installToken: '' # Used for MEC Configurations

  # Used only if the storage or backend server were installed in a separate helm release
  backendReleaseName:
  storageReleaseName:

  # Additional collector.properties
  extraCollectorProperties: ''
  # Example:
  #extraCollectorProperties: |-
  #  takipi.http.proxy=http://myproxy.com
  #  takipi.https.proxy=https://myproxy.com

replicaCount: 1

image:
  repository: overops/collector
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: false
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations: {}
podSecurityContext:
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
securityContext: {}

service:
  loadBalancerType: ""
  type: ClusterIP
  port: 6060

livenessProbe:
  enabled: true
  periodSeconds: 10
  failureThreshold: 3
  successThreshold: 1
  timeoutSeconds: 1
 

# The OverOps collector does not use HTTP/HTTPs but TCP therefore K8S Ingress is not directly supported
# many Ingress Controller support TCP but is spefific to the Controller. Please refer to your
# Ingress Controller for more info.
# ingress:
#  enabled: false

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. 
  # If you do want to specify resources, adjust them to Overops collector pre requirements,
  # as described in https://doc.overops.com/docs/overops-installation-requirements#section-collector-system-requirements .
  # or simply uncomment the following lines :
  #   resources:
  #     requests:
  #       memory: "4G"
  #       cpu: "2"
  #     limits:
  #       cpu: "4"
  #       memory: "8G"

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 70

nodeSelector: {}
tolerations: []
affinity: {}

updateStrategy: RollingUpdate
podManagementPolicy: OrderedReady
terminationGracePeriodSeconds: 30

## Persist data to a persistent volume
## Enabling storage the collector will use a Stateful Set rather than a Deployment.
persistence:
  enabled: false
  ## database data Persistent Volume Storage Class
  ## If defined, storageClassName: <storageClass>
  ## If set to "-", storageClassName: "", which disables dynamic provisioning
  ## If undefined (the default) or set to null, no storageClassName spec is
  ##   set, choosing the default provisioner.  (gp2 on AWS, standard on
  ##   GKE, AWS & OpenStack)
  ##
  # storageClass: "-"  
  accessModes:
    - ReadWriteOnce
  size: 1Gi
  annotations: {}  