apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "overops-server.fullname" . }}-config
  labels:
    {{- include "overops-server.labels" . | nindent 4 }}
data:
  application.properties: |-
    logging.level.root = {{ .Values.overops.loglevel }}

    spring.jpa.hibernate.ddl-auto=update
{{- if .Values.overops.rabbitQueue.enabled }}
    spring.profiles.active=mysql,msg_rabbit,service_stats,retry
{{- end }}
{{- if .Values.overops.redis.enabled }}
    spring.cache.type=redis
    spring.cache.redis.enable-statistics=true
    spring.redis.host={{ .Values.overops.redis.host }}
    spring.redis.port={{ .Values.overops.redis.port }}
    management.health.redis.enabled=true
{{- end }}
{{- if and .Values.config.enableExtraAppConfig .Values.config.applicationProperties }}
  {{ .Values.config.applicationProperties | nindent 4 }}
{{- end }}

  application-mysql.properties: |-
    spring.datasource.url=jdbc:mysql://{{ template "mysql.hostname" . }}:{{ .Values.mysql.service.port }}/overops?useLegacyDatetimeCode=false&rewriteBatchedStatements=true
    spring.datasource.username={{ .Values.mysql.mysqlUser }}
    spring.datasource.password=${DB_PASS}


{{- if .Values.overops.rabbitQueue.enabled }}
  application-msg_rabbit.properties: |-
    spring.rabbitmq.host={{ .Values.overops.rabbitQueue.service }}
    spring.rabbitmq.port={{ .Values.overops.rabbitQueue.port }}
    spring.rabbitmq.username={{ .Values.overops.rabbitQueue.username }}
    spring.rabbitmq.password=${RMQ_PASS}

    overops.exchange.name={{ .Values.overops.rabbitQueue.exchange }}
{{- end }}

  my.server.properties: |-
    FRONTEND_HOST={{ .Values.overops.frontendURL }}
    {{- if .Values.overops.takipiHost }}
    TAKIPI_HOST={{ .Values.overops.takipiHost }}
    {{- end }}

    LOCAL_DEFAULT_USER_JSON:  {"email": {{ .Values.overops.defaultUser | quote }}, "password": "${DEFAULT_PASS}", "first_name": {{ .Values.overops.defaultUserFirst | quote }}, "last_name": {{ .Values.overops.defaultUserLast | quote }}}
    LOCAL_DEFAULT_USER_SERVICE_SECRET_KEY: {{ .Values.overops.defaultUserServiceKey }}
    LOCAL_GENERATE_FIRST_USER_SERVICE_AND_LABELS=true
    LOCAL_GENERATE_DEFAULT_PRESETS=true
    LOCAL_GENERATE_DEFAULT_BADGES=true

    WORKERS_EXECUTOR_CPU_THREAD_POOL_SIZE=3
    WORKERS_EXECUTOR_IO_THREAD_POOL_SIZE=6
    WORKERS_EXECUTOR_SQL_THREAD_POOL_SIZE=6
  {{- if and .Values.config.enableExtraConfig .Values.config.myServerProperties  }}
  {{ .Values.config.myServerProperties | nindent 4 }}
  {{- end }}

{{- if and .Values.config.enableExtraConfig .Values.config.extraConfigurationFiles }}
{{- range $key, $val := .Values.config.extraConfigurationFiles }}
  {{ $key }}: |-
{{ $val | indent 4}}
{{- end }}
{{- end }}

  {{- if .Values.overops.agentSidecar.enabled }}
  agent.properties: |-
    # Agent Properties File
    # i.e. takipi.max.depth=10
  {{- if .Values.overops.agentSidecar.agentProperties }}
  {{ .Values.overops.agentSidecar.agentProperties | nindent 4 }}
  {{- end }}
  {{- end }}
