apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "overops-receiver-server.fullname" . }}-config
  labels:
    {{- include "overops-receiver-server.labels" . | nindent 4 }}
data:
  application.properties: |-
    logging.level.root = {{ .Values.overops.loglevel }}

    spring.jpa.hibernate.ddl-auto=update

{{- if eq .Values.overops.rabbitQueue.type "sql" }}
    spring.profiles.active=mysql,msg_rabbit,sqli,sql_locinv,sql_metric
{{- else if eq .Values.overops.rabbitQueue.type "agent" }}
    spring.profiles.active=mysql,msg_rabbit,agent_stats
{{- else if eq .Values.overops.rabbitQueue.type "decompile" }}
    spring.profiles.active=mysql,msg_rabbit,decompile
{{- else if eq .Values.overops.rabbitQueue.type "custom" }}
    spring.profiles.active={{ .Vaules.overops.rabbitQueue.customType }}
{{- else }}
    spring.profiles.active=mysql,msg_rabbit,hit
{{- end }}
{{- if .Values.overops.redis.enabled }}
    spring.cache.type=redis
    spring.cache.redis.enable-statistics=true
    spring.redis.host={{ .Values.overops.redis.host }}
    spring.redis.port={{ .Values.overops.redis.port }}
    management.health.redis.enabled=true
{{- end }}
{{- if and .Values.config.enableExtraAppConfig .Values.config.applicationProperties }}
  {{ .Values.config.applicationProperties | nindent 4 }}
{{- end }}

  application-mysql.properties: |-
    spring.datasource.url=jdbc:mysql://{{ .Values.overops.mysql.url }}:{{ .Values.overops.mysql.port }}/overops?useLegacyDatetimeCode=false&rewriteBatchedStatements=true
    spring.datasource.username={{ .Values.overops.mysql.user}}
    spring.datasource.password=${DB_PASS}

  application-msg_rabbit.properties: |-
    spring.rabbitmq.host={{ .Values.overops.rabbitQueue.service }}
    spring.rabbitmq.port={{ .Values.overops.rabbitQueue.port }}
    spring.rabbitmq.username={{ .Values.overops.rabbitQueue.username }}
    spring.rabbitmq.password=${RMQ_PASS}

    overops.exchange.name={{ .Values.overops.rabbitQueue.exchange }}

  {{- if .Values.overops.agentSidecar.enabled }}
  agent.properties: |-
    # Agent Properties File
    # i.e. takipi.max.depth=10
  {{- if .Values.overops.agentSidecar.agentProperties }}
  {{ .Values.overops.agentSidecar.agentProperties | nindent 4 }}
  {{- end }}
  {{- end }}
