{{- if  .Values.persistence.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "overops-collector.fullname" . }}-headless
  labels:
    {{- include "overops-collector.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  publishNotReadyAddresses: true  
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 6060
      protocol: TCP
      name: collector
  selector:
    {{- include "overops-collector.selectorLabels" . | nindent 4 }}
{{- end }}